import cv2

DATA_KEY_IN_API_RESPONSE = "data"
IMAGE_URL_KEY_IN_RESPONSE_DATA = "url"

EMPTY_TEXT = "blank"

MEME_FONT_SCALE_RATIO = 0.8 / 256
TEXT_OY_CENTER = 0.85
TEXT_THICKNESS = 2
TEXT_BORDER_THICKNESS = 6
TEXT_COLOR = (255, 255, 255)
TEXT_BORDER_COLOR = (0, 0, 0)
TEXT_LINE_CHARACTERS = 15
FONT = cv2.FONT_HERSHEY_DUPLEX
NATURAL_TEXT_SEPARATORS = {" ", ".", ",", "?", "!"}
IMAGE_PADDING_COLOR = (255, 255, 255)
PADDING_SIZE_RATIO = 5 / 256
FOOTER_SIZE_RATIO = 60 / 256
